https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node
https://www.techiediaries.com/vuejs-php-mysql-rest-crud-api-tutorial/
https://www.microsoft.com/en-us/sql-server/developer-get-started/node/windows/step/2.html
https://docs.microsoft.com/en-us/azure/sql-database/sql-database-connect-query-nodejs
https://dzone.com/articles/creating-real-time-data-aapplication-using-vuejs
https://makitweb.com/fetch-records-from-mysql-database-with-vue-js-and-php/
https://koukia.ca/getting-started-with-vuejs-nodejs-and-azure-cosmosdb-35dadbf2dd3c
https://stackoverflow.com/questions/857670/how-to-connect-to-sql-server-database-from-javascript-in-the-browser
https://github.com/vuetifyjs/webpack-ssr
https://stackoverflow.com/questions/48919886/how-to-make-mssql-connection-using-node-js-in-vue-js-frontend
http://www.frankysnotes.com/2017/11/how-to-access-sql-database-from-azure.html
https://medium.com/@jocapc/creating-rest-api-with-nodejs-and-sql-server-azure-sql-4933fd3fb2be
https://www.concurrency.com/blog/january-2017/connect-to-azure-sql-database-with-nodejs-and-mssq
https://docs.microsoft.com/en-us/azure/javascript/node-samples-services-database
https://dzone.com/articles/sql-with-visual-studio-code
https://www.microsoft.com/en-us/sql-server/sql-server-downloads
https://www.youtube.com/watch?v=J593Tak3tCg
https://www.sqlservercentral.com/articles/building-restful-apis-using-node-js-express-js-and-ms-sql-server
